language: node_js
dist: trusty
addons:
  chrome: stable
node_js:
- '8.0'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
- export PATH="$HOME/.yarn/bin:$PATH"
#- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &
- google-chrome-stable --headless --disable-gpu --no-sandbox http://localhost:8080 &
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm start &
script:
- npm run typecheck
- npm run test
- npm run e2e
env:
  global:
  - FACEBOOK_CLIENT_ID: 1922649294663455
  - CONTACTLAB_FBUSER_USER: harry_fllogxr_valtchanovsen@tfbnw.net
  - secure: DHZWkLhnzEFX4NNqN7hxFnfIz8VJWZOuj6vEbuVj7LoHJEtlWJQMkSWny6gmI1JqVD7BjJBypumtjWJt98tp77+4fX8r4FtYJ0X+kAQc3aVgq7Arx7BlcpbDY+YGdighyBIXlHOajv5ACwUZhB142WSVbXl5pEsEw11DjjdYMUjLO1Xc6LG4teeKanpDYo1n8WMaqjaZgiJNiivORH6h9x/bHEo395L4gHDuNyCLa9QbWWe2VIdX/vTncGzD6UVSrfnAhlpmV2pka1QSxLGDZPEORDhalpFEDxTXrFOO4bG4MXrzZzM2jFVWH9jfvEUNJN65ya7SMXh9t2ldvKFxnF0qGBsN5x6o0qp8JKQhG3J0DHqhf+hKoUGkMLn17+bI8tFI2N+zfUKWesMFvfUlBuMVXdt2ryL6E5M9vtYubFvbSYxUjIAH8fLC4sL4XyeLsGaBg9ONSYuIfmf+fmXHv9pXIPaNvHLcYaqvQHqWIkZzrtgxWVc5ohuevNDW1zrp8qVRICCnfFjTJGTJ0NUbF8AnaXYf4z/SzgxTWFUN30MurFWE2ajubAQXVV16p4zOXv9kLqJJ36eUVuQtYLaVK4OpKKk4J54uIwexTOaFxv+AAn1Tz6IwRArbol/x4f6TByBhaz9JhuMB5FaaDpUVnr40XnCqIXPU2ir1q9Q0Axg=
